import nodemailer from "nodemailer";
import type { Report } from "./types";
import { DEPARTMENT_EMAIL } from "./constants";

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

function getPriorityLabel(priority: string): string {
  const labels: Record<string, string> = {
    critical: "🔴 CRITICAL",
    high: "🟠 HIGH",
    medium: "🟡 MEDIUM",
    low: "🟢 LOW",
  };
  return labels[priority] ?? priority.toUpperCase();
}

function buildEmailHtml(report: Report): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; }
    .header { background: #00539F; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
    .header h1 { margin: 0; font-size: 22px; }
    .header p { margin: 4px 0 0; font-size: 14px; opacity: 0.85; }
    .body { padding: 20px; border: 1px solid #ddd; border-top: none; border-radius: 0 0 8px 8px; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 13px; font-weight: bold; }
    .critical { background: #fee2e2; color: #991b1b; }
    .high { background: #ffedd5; color: #9a3412; }
    .medium { background: #fef9c3; color: #854d0e; }
    .low { background: #dcfce7; color: #166534; }
    .field { margin: 12px 0; }
    .label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
    .value { font-size: 15px; margin-top: 2px; }
    .divider { border: none; border-top: 1px solid #eee; margin: 16px 0; }
    .footer { font-size: 12px; color: #999; margin-top: 16px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>FixIt AI — New Work Order</h1>
    <p>University of Delaware Facilities Management</p>
  </div>
  <div class="body">
    <div class="field">
      <div class="label">Priority</div>
      <div class="value">
        <span class="badge ${report.priority}">${getPriorityLabel(report.priority)}</span>
        ${report.safety_concern ? '<span style="margin-left:8px;color:#dc2626;font-weight:bold;">⚠️ Safety Concern</span>' : ""}
      </div>
    </div>

    <hr class="divider" />

    <div class="field">
      <div class="label">Location</div>
      <div class="value">${report.building}${report.floor ? `, Floor ${report.floor}` : ""}${report.room ? `, Room ${report.room}` : ""}</div>
    </div>

    <div class="field">
      <div class="label">Trade</div>
      <div class="value">${report.trade.charAt(0).toUpperCase() + report.trade.slice(1).replace("_", " ")}</div>
    </div>

    <div class="field">
      <div class="label">AI Description</div>
      <div class="value">${report.ai_description}</div>
    </div>

    <div class="field">
      <div class="label">Suggested Action</div>
      <div class="value">${report.suggested_action}</div>
    </div>

    <div class="field">
      <div class="label">Reporter Description</div>
      <div class="value">${report.description || "None provided"}</div>
    </div>

    <hr class="divider" />

    <div class="field">
      <div class="label">Estimated Cost</div>
      <div class="value">${report.estimated_cost}</div>
    </div>

    <div class="field">
      <div class="label">Estimated Repair Time</div>
      <div class="value">${report.estimated_time}</div>
    </div>

    <div class="field">
      <div class="label">AI Confidence</div>
      <div class="value">${Math.round(report.confidence_score * 100)}%</div>
    </div>

    ${
      report.reporter_name || report.reporter_email
        ? `
    <hr class="divider" />
    <div class="field">
      <div class="label">Reported By</div>
      <div class="value">${report.reporter_name || ""}${report.reporter_email ? ` &lt;${report.reporter_email}&gt;` : ""}</div>
    </div>`
        : ""
    }

    <hr class="divider" />
    <div class="field">
      <div class="label">Report ID</div>
      <div class="value" style="font-family:monospace;font-size:13px;">${report.id}</div>
    </div>
    <div class="field">
      <div class="label">Submitted At</div>
      <div class="value">${new Date(report.created_at).toLocaleString("en-US", { timeZone: "America/New_York" })} ET</div>
    </div>

    <div class="footer">
      This work order was automatically generated by FixIt AI. Powered by OpenAI Vision + UDel Facilities.
    </div>
  </div>
</body>
</html>`;
}

export async function sendPinEmail(
  email: string,
  pin: string,
  role: string
): Promise<void> {
  await transporter.sendMail({
    from: `"FixIt AI — UDel" <${process.env.GMAIL_USER}>`,
    to: email,
    subject: `Your FixIt AI Login Code: ${pin}`,
    html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; }
    .header { background: #00539F; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
    .header h1 { margin: 0; font-size: 22px; }
    .body { padding: 24px; border: 1px solid #ddd; border-top: none; border-radius: 0 0 8px 8px; text-align: center; }
    .pin { font-size: 36px; font-weight: bold; letter-spacing: 8px; color: #00539F; margin: 24px 0; font-family: monospace; }
    .role { display: inline-block; background: #FFD200; color: #333; padding: 4px 12px; border-radius: 20px; font-size: 13px; font-weight: bold; }
    .footer { font-size: 12px; color: #999; margin-top: 16px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>FixIt AI — Login Verification</h1>
  </div>
  <div class="body">
    <p>Your one-time login code is:</p>
    <div class="pin">${pin}</div>
    <p>Logging in as: <span class="role">${role.toUpperCase()}</span></p>
    <p style="color:#666;font-size:14px;">This code expires in 10 minutes.</p>
    <div class="footer">
      FixIt AI — University of Delaware Campus Maintenance
    </div>
  </div>
</body>
</html>`,
  });
}

export async function sendAssignmentEmail(
  techEmail: string,
  techName: string,
  report: Report
): Promise<void> {
  await transporter.sendMail({
    from: `"FixIt AI — UDel Facilities" <${process.env.GMAIL_USER}>`,
    to: techEmail,
    subject: `[ASSIGNED] ${report.trade.replace("_", " ").toUpperCase()} issue at ${report.building}${report.room ? `, Room ${report.room}` : ""} — WO #${report.id.slice(0, 8)}`,
    html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; }
    .header { background: #00539F; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
    .header h1 { margin: 0; font-size: 22px; }
    .body { padding: 20px; border: 1px solid #ddd; border-top: none; border-radius: 0 0 8px 8px; }
    .field { margin: 12px 0; }
    .label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
    .value { font-size: 15px; margin-top: 2px; }
    .divider { border: none; border-top: 1px solid #eee; margin: 16px 0; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 13px; font-weight: bold; }
    .critical { background: #fee2e2; color: #991b1b; }
    .high { background: #ffedd5; color: #9a3412; }
    .medium { background: #fef9c3; color: #854d0e; }
    .low { background: #dcfce7; color: #166534; }
  </style>
</head>
<body>
  <div class="header">
    <h1>FixIt AI — New Assignment</h1>
  </div>
  <div class="body">
    <p>Hi ${techName}, you have been assigned a new work order.</p>
    <div class="field">
      <div class="label">Priority</div>
      <div class="value"><span class="badge ${report.priority}">${getPriorityLabel(report.priority)}</span></div>
    </div>
    <div class="field">
      <div class="label">Location</div>
      <div class="value">${report.building}${report.floor ? `, Floor ${report.floor}` : ""}${report.room ? `, Room ${report.room}` : ""}</div>
    </div>
    <div class="field">
      <div class="label">Issue</div>
      <div class="value">${report.ai_description}</div>
    </div>
    <div class="field">
      <div class="label">Suggested Action</div>
      <div class="value">${report.suggested_action}</div>
    </div>
    <hr class="divider" />
    <div class="field">
      <div class="label">Estimated Time</div>
      <div class="value">${report.estimated_time}</div>
    </div>
    <p style="font-size:13px;color:#666;">Log in to the FixIt AI Technician Portal to accept this assignment.</p>
  </div>
</body>
</html>`,
  });
}

export async function sendEscalationEmail(opts: {
  to: string;
  subject: string;
  text: string;
  html: string;
}): Promise<void> {
  await transporter.sendMail({
    from: `"FixIt AI — UDel Facilities" <${process.env.GMAIL_USER}>`,
    to: opts.to,
    subject: opts.subject,
    text: opts.text,
    html: opts.html,
  });
}

// --- Automated Follow-up Emails to Reporters ---
export async function sendReporterStatusEmail(
  reporterEmail: string,
  report: Report,
  newStatus: string,
  extra?: { techName?: string; completionNotes?: string }
): Promise<void> {
  const statusMessages: Record<string, { subject: string; heading: string; body: string; color: string }> = {
    dispatched: {
      subject: `Your report has been dispatched — ${report.building}`,
      heading: "Your Report Has Been Dispatched",
      body: `A technician has been assigned to address the ${report.trade.replace("_", " ")} issue at ${report.building}${report.room ? `, Room ${report.room}` : ""}. ${extra?.techName ? `Assigned to: ${extra.techName}.` : ""}`,
      color: "#3b82f6",
    },
    in_progress: {
      subject: `Work has started on your report — ${report.building}`,
      heading: "A Technician Is Working On It",
      body: `${extra?.techName || "A technician"} has started working on the ${report.trade.replace("_", " ")} issue at ${report.building}${report.room ? `, Room ${report.room}` : ""}.`,
      color: "#f59e0b",
    },
    resolved: {
      subject: `Your report has been resolved — ${report.building}`,
      heading: "Issue Resolved!",
      body: `The ${report.trade.replace("_", " ")} issue at ${report.building}${report.room ? `, Room ${report.room}` : ""} has been resolved.${extra?.completionNotes ? ` Notes: ${extra.completionNotes}` : ""}`,
      color: "#22c55e",
    },
  };

  const msg = statusMessages[newStatus];
  if (!msg) return;

  await transporter.sendMail({
    from: `"FixIt AI — UDel" <${process.env.GMAIL_USER}>`,
    to: reporterEmail,
    subject: msg.subject,
    html: `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; }
    .header { background: ${msg.color}; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
    .header h1 { margin: 0; font-size: 20px; }
    .body { padding: 20px; border: 1px solid #ddd; border-top: none; border-radius: 0 0 8px 8px; }
    .status { display: inline-block; padding: 6px 16px; border-radius: 20px; font-weight: bold; font-size: 14px; color: white; background: ${msg.color}; }
    .footer { font-size: 12px; color: #999; margin-top: 16px; }
  </style>
</head>
<body>
  <div class="header"><h1>FixIt AI — Status Update</h1></div>
  <div class="body">
    <h2 style="margin-top:0;">${msg.heading}</h2>
    <p>${msg.body}</p>
    <p><strong>Report:</strong> ${report.ai_description || report.description}</p>
    <p><strong>Location:</strong> ${report.building}${report.floor ? `, Floor ${report.floor}` : ""}${report.room ? `, Room ${report.room}` : ""}</p>
    <hr style="border:none;border-top:1px solid #eee;margin:16px 0;">
    <p class="footer">Report #${report.id.slice(0, 8)} • FixIt AI — University of Delaware</p>
  </div>
</body>
</html>`,
  });
}

// --- SLA Escalation Email to Manager ---
export async function sendSLAEscalationEmail(opts: {
  reports: { id: string; building: string; room: string; trade: string; priority: string; created_at: string; minutesElapsed: number }[];
  reason: string;
}): Promise<void> {
  const rows = opts.reports.map((r) =>
    `<tr><td style="padding:8px;border-bottom:1px solid #eee;">#${r.id.slice(0, 8)}</td><td style="padding:8px;border-bottom:1px solid #eee;">${r.building}${r.room ? `, ${r.room}` : ""}</td><td style="padding:8px;border-bottom:1px solid #eee;">${r.trade}</td><td style="padding:8px;border-bottom:1px solid #eee;color:${r.priority === "critical" ? "#ef4444" : r.priority === "high" ? "#f97316" : "#eab308"};">${r.priority.toUpperCase()}</td><td style="padding:8px;border-bottom:1px solid #eee;">${r.minutesElapsed}m ago</td></tr>`
  ).join("");

  await transporter.sendMail({
    from: `"FixIt AI — UDel Facilities" <${process.env.GMAIL_USER}>`,
    to: "facilities-manager@udel.edu",
    subject: `⚠ SLA ESCALATION: ${opts.reports.length} report(s) need attention — ${opts.reason}`,
    html: `
<!DOCTYPE html>
<html>
<head><style>body{font-family:Arial,sans-serif;color:#333;max-width:600px;margin:0 auto;} table{width:100%;border-collapse:collapse;} th{text-align:left;padding:8px;background:#f9fafb;border-bottom:2px solid #ddd;font-size:12px;text-transform:uppercase;color:#666;}</style></head>
<body>
  <div style="background:#ef4444;color:white;padding:16px 20px;border-radius:8px 8px 0 0;">
    <h2 style="margin:0;">⚠ SLA Escalation Alert</h2>
    <p style="margin:4px 0 0;opacity:0.9;font-size:14px;">${opts.reason}</p>
  </div>
  <div style="padding:20px;border:1px solid #ddd;border-top:none;border-radius:0 0 8px 8px;">
    <table><thead><tr><th>ID</th><th>Location</th><th>Trade</th><th>Priority</th><th>Elapsed</th></tr></thead><tbody>${rows}</tbody></table>
    <p style="font-size:12px;color:#999;margin-top:16px;">Auto-escalated by FixIt AI SLA Engine</p>
  </div>
</body></html>`,
  });
}

// --- Preventive Maintenance Work Order Email ---
export async function sendPreventiveMaintenanceEmail(opts: {
  trade: string;
  count: number;
  buildings: string[];
  windowDays: number;
}): Promise<void> {
  await transporter.sendMail({
    from: `"FixIt AI — UDel Facilities" <${process.env.GMAIL_USER}>`,
    to: "facilities-manager@udel.edu",
    subject: `🔧 Preventive Maintenance Auto-Generated: ${opts.trade.replace("_", " ")} (${opts.count} incidents in ${opts.windowDays} days)`,
    html: `
<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;color:#333;max-width:600px;margin:0 auto;">
  <div style="background:#f59e0b;color:white;padding:16px 20px;border-radius:8px 8px 0 0;">
    <h2 style="margin:0;">🔧 Preventive Maintenance Work Order</h2>
    <p style="margin:4px 0 0;opacity:0.9;font-size:14px;">Auto-generated by Pattern Detection</p>
  </div>
  <div style="padding:20px;border:1px solid #ddd;border-top:none;border-radius:0 0 8px 8px;">
    <p><strong>Trade:</strong> ${opts.trade.replace("_", " ").toUpperCase()}</p>
    <p><strong>Pattern:</strong> ${opts.count} reports in the last ${opts.windowDays} days</p>
    <p><strong>Affected Buildings:</strong> ${opts.buildings.join(", ")}</p>
    <p><strong>Recommended Action:</strong> Schedule a comprehensive ${opts.trade.replace("_", " ")} inspection across affected buildings to identify and address root causes before further incidents occur.</p>
    <hr style="border:none;border-top:1px solid #eee;margin:16px 0;">
    <p style="font-size:12px;color:#999;">Auto-generated by FixIt AI Predictive Maintenance Engine</p>
  </div>
</body></html>`,
  });
}

export async function sendDispatchEmail(report: Report): Promise<void> {
  const to = DEPARTMENT_EMAIL[report.trade];
  const priorityLabel = getPriorityLabel(report.priority);

  await transporter.sendMail({
    from: `"FixIt AI — UDel Facilities" <${process.env.GMAIL_USER}>`,
    to,
    subject: `[${priorityLabel}] ${report.trade.replace("_", " ").toUpperCase()} issue at ${report.building} — Work Order #${report.id.slice(0, 8)}`,
    html: buildEmailHtml(report),
  });
}
